## 多項式の項の求め方

$$
\begin{equation}
\left\{ \,
    \begin{aligned}
    \theta_z(s) &= a_1 s^2 + a_2 s \\
    y(s) &= (l_0 + \Delta x) (\frac{1}{3}a_1 s^3 + \frac{1}{2}a _2s^2) \\
    \end{aligned}
\right.
\end{equation}
$$

$$
\begin{align}
y(s) &= \int_{0}^{s} \theta_z(s) \mathrm{d}x \\
     &= \int_{0}^{s} \theta_z(s) \frac{\mathrm{d}x}{\mathrm{d}s} \mathrm{d}s \\
     &= \int_{0}^{s} (a_1 s^2 + a_2 s) (l_0 + \Delta x) \mathrm{d}s \\
     &= (l_0 + \Delta x) (\frac{1}{3}a_1 s^3 + \frac{1}{2}a _2s^2) \\
\end{align}
$$

$$\left(\theta_z(1)=\theta_{z1}, y(1)=y_1 \right)$$

$$
\begin{align}
\left[ \begin{array}{cccc}
1 &1  \\
\frac{l_0 + \Delta x}{3} & \frac{l_0 + \Delta x}{2} \\
\end{array}\right]
\left[ \begin{array}{cccc}
a_1 \\
a_2 \\
\end{array}\right]
&=
\left[ \begin{array}{cccc}
\theta_{z1} \\
y_1 \\
\end{array}\right] \\\\
\left[ \begin{array}{cccc}
a_1 \\
a_2 \\
\end{array}\right]
&=
\left[ \begin{array}{cccc}
3  &-\frac{6}{l_0 + \Delta x} \\
-2 & \frac{6}{l_0 + \Delta x} \\
\end{array}\right]
\left[ \begin{array}{cccc}
\theta_{z1} \\
y_1 \\
\end{array}\right]
\end{align}
$$


## 多項式近似を用いた梁の変位関数

$$
\begin{align}
x(s) &= (l_0 + \Delta x) s \\\\
y(s) &= (l_0 + \Delta x) (\frac{1}{3}a_1 s^3 + \frac{1}{2}a _2 s^2) \\\\
z(s) &= (l_0 + \Delta x) (- \frac{1}{3}a_3 s^3 - \frac{1}{2}a_4 s^2) \\\\
\theta_x(s) &= \Delta \theta_x s \\\\
\theta_y(s) &= a_3 s^2 + a_4 s \\\\
\theta_z(s) &= a_1 s^2 + a_2 s \\\\
(0 \leq &s \leq 1) \\\\
\end{align}
$$



## 梁の断面位置を求める近似式について

$$
\begin{align}
\vec{x}(s) &= \vec{x}_0 + q_0 \otimes \left( \left[ \begin{array}{cccc} (l_0 + \Delta x)s \\ (l_0 + \Delta x) (\frac{1}{3}a_1 s^3 + \frac{1}{2}a_2s^2) \\ -(l_0 + \Delta x) (\frac{1}{3}a_3 s^3 + \frac{1}{2}a_4 s^2) \\ \end{array}\right] + \Delta q(s) \otimes \left[ \begin{array}{cccc} 0 \\ u \\ v \\ \end{array}\right]\right) \\\\
&\approx \vec{x}_0 + q_0 \otimes \left( (l_0 + \Delta x) \left[ \begin{array}{cccc} s \\ \frac{1}{3}a_1 s^3 + \frac{1}{2}a _2s^2 \\ - \frac{1}{3}a_3 s^3 - \frac{1}{2}a_4 s^2 \\ \end{array}\right] + \left[ \begin{array}{cccc} -\theta_z u' -\theta_y v' \\ u' \\ v' \\ \end{array}\right]\right) \\\\
\end{align}
$$

$$
\left( \Delta q_x \otimes \left[ \begin{array}{cccc} 0 \\ u \\ v \\ \end{array}\right] = \left[ \begin{array}{cccc} 0 \\ u' \\ v' \\ \end{array}\right] \right) \\\\
$$

$$
\left[ \begin{array}{cccc} x_0 \\ y_0 \\ z_0 \\ \end{array}\right] \approx (l_0 + \Delta x) \left[ \begin{array}{cccc} s \\ \frac{1}{3}a_1 s^3 + \frac{1}{2}a _2s^2 \\ - \frac{1}{3}a_3 s^3 - \frac{1}{2}a_4 s^2 \\ \end{array}\right] + \left[ \begin{array}{cccc} -(a_1 s^2+a_2 s) u' -(a_3 s^2+a_4 s) v' \\ u' \\ v' \\ \end{array}\right]
$$

1. 高さからおおよその$s'$を求める．
1. $s'$からおおよその$y', z'$を求める．
1. $y', z'$からおおよその$u'', v''$を求める．
1. $x$成分について$s$の2次関数を解きたい．
1. $s$では2次の項の値が小さすぎ誤差が大きくなることが予想されるため，$s = 1/t$の関係を持つ$t$について解く．

$$
\begin{align}
x_0 &= (l_0 + \Delta x) s -(a_1 s^2+a_2 s) u'' -(a_3 s^2+a_4 s) v'' \\\\
0   &= (a_1 u'' + a_3 v'') s^2 + \left(a_2 u'' + a_4 v'' - (l_0 + \Delta x)\right) s + x_0 \\\\
    &= (a_1 u'' + a_3 v'') \frac{1}{t^2} + \left(a_2 u'' + a_4 v'' - (l_0 + \Delta x) \right) \frac{1}{t} + x_0 \\\\
    &= x_0 t^2  + \left(a_2 u'' + a_4 v'' - (l_0 + \Delta x) \right) t + (a_1 u'' + a_3 v'') \\\\
t   &= \frac{-b\pm\sqrt{b^2-4ac}}{2a}
\end{align}
$$

$c=0$を代入したときに，$t=0$では明らかにおかしいため，±の符号は$-$である．よって，

$$
s = \frac{2a}{-b - \sqrt{b^2-4ac}}
$$



In [9]:
import numpy as np  # The next command is required: "pip install -U numpy"
import quaternion   # The next command is required: "pip install numpy-quaternion"


In [10]:
def Beam_Matrix(l0):
    l0_1 = 1 / l0
    l0_2 = 1 / l0 / l0
    l0_3 = 1 / l0 / l0 / l0
    
    ab_inv0 = np.array([[-6 * l0_3, 3 * l0_2], [ 6 * l0_2, -2 * l0_1]])
    cd_inv0 = np.array([[ 6 * l0_3, 3 * l0_2], [-6 * l0_2, -2 * l0_1]])

    return ab_inv0, cd_inv0


def Beam_Coefficient(x0, q0, x1, q1, l0, ab_inv0, cd_inv0):
    q0_inv = q0.inverse()
    x1_ = quaternion.rotate_vectors(q0_inv, x1 - x0)

    dx = x1_ - np.array([l0, 0, 0])
    dq = q0_inv * q1 * 2
    
    ab0 = ab_inv0 @ np.array([dx[1], dq.z])
    cd0 = cd_inv0 @ np.array([dx[2], dq.y])
    
    dx0  = l0 + dx[0]
    dqx0 = dq.x
    
    return ab0, cd0, dx0, dqx0

# 
def Beam_Displacement(x0, q0, l0, s, ab0, cd0, dx0, dqx0):
    
    ls  = l0 * s
    ls2 = ls * ls
    ls3 = ls2 * ls
    
    x_ = dx0 * s
    y_ = ab0[0] / 3 * ls3 + ab0[1] / 2 * ls2
    z_ =-cd0[0] / 3 * ls3 - cd0[1] / 2 * ls2
    
    tx_ = dqx0 * s
    ty_ = cd0[0] * ls2 + cd0[1] * ls
    tz_ = ab0[0] * ls2 + ab0[1] * ls
    
    xs = x0 + quaternion.rotate_vectors(q0, np.array([x_,y_,z_]))
    qs = q0 * quaternion.from_float_array([1, tx_/2, ty_/2, tz_/2]).normalized()
    
    return xs, qs


In [11]:
r0 = 0.1
l0 = 1.0
E0 = 2e11
G0 = 8e10

A0 = np.pi * r0**2
I0 = np.pi / 4 * r0**4
J0 = np.pi / 2 * r0**4

kxx =  1 * E0 * A0 / l0
kyy = 12 * E0 * I0 / l0**3
kyt =  6 * E0 * I0 / l0**2
ktx =  1 * G0 * J0 / l0
kty =  2 * E0 * I0

x0 = np.array([0.0, 0.0, 0.0])
q0 = quaternion.from_float_array([1,0,0,0])
q1 = quaternion.from_float_array([1, 0, 0, 3.17e-05 / 2]).normalized()
x_unit = np.array([1, 0, 0])

x1 = x0 + l0 * (quaternion.rotate_vectors(q0, x_unit)) + np.array([0, 0.0212e-3, 0])

ab_inv0, cd_inv0 = Beam_Matrix(l0)
ab0, cd0, dx0, dqx0 = Beam_Coefficient(x0, q0, x1, q1, l0, ab_inv0, cd_inv0)
xs, qs = Beam_Displacement(x0, q0, l0, 0.0, ab0, cd0, dx0, dqx0)

print(xs, qs)
print(x0, q0)

xs, qs = Beam_Displacement(x0, q0, l0, 1.0, ab0, cd0, dx0, dqx0)

print(xs, qs)
print(x1, q1)


[0. 0. 0.] quaternion(1, 0, 0, 0)
[0. 0. 0.] quaternion(1, 0, 0, 0)
[1.00e+00 2.12e-05 0.00e+00] quaternion(0.999999999874389, 0, 0, 1.58499999960181e-05)
[1.00e+00 2.12e-05 0.00e+00] quaternion(0.999999999874389, 0, 0, 1.58499999980091e-05)


In [12]:
ab1, cd1, dx1, dqx1 = Beam_Coefficient(x1, q1, x0, q0, l0, ab_inv0, cd_inv0)
xs, qs = Beam_Displacement(x1, q1, l0, 0.0, ab1, cd1, dx1, dqx1)

print(xs, qs)
print(x1, q1)

xs, qs = Beam_Displacement(x1, q1, l0, 1.0, ab1, cd1, dx1, dqx1)

print(xs, qs)
print(x0, q0)


[1.00e+00 2.12e-05 0.00e+00] quaternion(0.999999999874389, 0, 0, 1.58499999980091e-05)
[1.00e+00 2.12e-05 0.00e+00] quaternion(0.999999999874389, 0, 0, 1.58499999980091e-05)
[ 0.00000000e+00 -6.77626358e-21  0.00000000e+00] quaternion(1, 0, 0, 1.99092722559871e-15)
[0. 0. 0.] quaternion(1, 0, 0, 0)


In [13]:
n0 = 100
s_array = np.linspace(0, 1, n0)
x_array = np.zeros([3, n0])
q_array = np.zeros([3, n0])
x_array_= np.zeros([3, n0])

for i0 in range(n0):
    xs, qs = Beam_Displacement(x0, q0, l0, s_array[i0], ab0, cd0, dx0, dqx0)
    x_array[:,i0] = xs
    q_array[:,i0] = quaternion.rotate_vectors(qs, x_unit)
    
    xs, qs = Beam_Displacement(x1, q1, l0, 1 - s_array[i0], ab1, cd1, dx1, dqx1)
    x_array_[:,i0] = xs
    
u_array = x_array[:, 2:] - x_array[:, :-2]
u_array = u_array / np.sqrt(np.square(u_array).sum(0))



bbbb

$$
\begin{align}
x(s) &= (l_0 + \Delta x) s \\\\
y(s) &= \frac{a}{3}(l_0 s)^3 + \frac{b}{2}(l_0 s)^2 \\\\
z(s) &= -\frac{c}{3}(l_0 s)^3 - \frac{d}{2}(l_0 s)^2 \\\\
\theta_x(s) &= \Delta \theta_x s \\\\
\theta_y(s) &= c(l_0 s)^2 + d(l_0 s) \\\\
\theta_z(s) &= a(l_0 s)^2 + b(l_0 s) \\\\
(0 \leq &s \leq 1) \\\\
\end{align}
$$

cccc

$$
\phi
$$
